app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Site Route
//Route::get('/', 'HomeController@index');
//Route::get('/open', 'HomeController@index');
Route::get('/', 'HomeController@index1');
Route::get('/home', 'HomeController@index1')->name('home');

// All Admin Route
Route::group(['namespace' => 'Admin'], function() {

    // Admin Auth Routes
    Route::get('admin-login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('admin-login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::get('register-schoolx', 'Auth\RegisterController@showRegistrationForm')->name('admin.register');
    Route::post('register-schoolx', 'Auth\RegisterController@register');
    
    // Dashboard Routes
    Route::get('admin-schoolx', 'AdminController@index')->name('admin-slf');

    // Users Route
    Route::resource('admin-schoolx/user', 'UserController');

    // Roles Route
    Route::resource('admin-schoolx/role', 'RoleController');

    // Permission Route
    Route::resource('admin-schoolx/permission', 'PermissionController');

    // News Routes
    Route::resource('admin-schoolx/news', 'NewsController');
    

});

Auth::routes();

app/app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\admin\permission;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;


class PermissionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = permission::all();
        return view ('backend.permissions.index', compact('permissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->can('permission.create')) {
            return view ('backend.permissions.create');
        } 
        
        return redirect(route('admin-slf'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:50|unique:permissions',
            'for_permission' => 'required'
        ]);

        $permission = new permission;

        $permission->name = $request->name;
        $permission->for_permission = $request->for_permission;
        $permission->admin_id = $request->admin_id;

        $permission->save();

        return redirect(route('permission.index'))->with('message', 'Permission Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\admin\permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function show(permission $permission)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\admin\permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function edit(permission $permission)
    {
        if (Auth::user()->can('permission.update')) {
            $permission = permission::where('id', $permission->id)->first();
            return view('backend.permissions.edit', compact('permission'));
        } 

        return redirect(route('admin-slf'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\admin\permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, permission $permission)
    {
        $this->validate($request, [
            'name' => 'required|max:50',
            'for_permission' => 'required'
        ]);

        $permission = permission::find($permission->id);

        $permission->name = $request->name;
        $permission->for_permission = $request->for_permission;
        $permission->admin_id = $request->admin_id;

        $permission->save();

        return redirect(route('permission.index'))->with('message', 'Permission Update Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\admin\permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function destroy(permission $permission)
    {
        permission::where('id', $permission->id)->delete();
        return redirect()->back()->with('message', 'Permission Deleted Successfully');
    }
}

app/resources/views/backend/permissions/create.blade.php
@extends('backend/layouts/app')

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Permissions
                <small>add, edit, delete permissions section</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Permissions</a></li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Permission Section</h3>
                        </div>

                        @include('include/messages')
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('permission.store') }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                            <div class="box-body">
                                <!-- left column -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="news-head"> Permission Name<code>*</code></label>
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter Permission name ..">
                                    </div>

                                    <div class="form-group">
                                        <label for="for-permission"> Permission for</label>
                                        <select name="for_permission" id="for_permission" class="form-control">
                                            <option selected disable>Select Permission for </option>
                                            <option value="user">User</option>
                                            <option value="post">Post</option>
                                            <option value="other">Other</option>
                                        </select>
                                    </div>
                                </div>

                                <!-- right column -->
                                <div class="col-md-6">

                                    
                                    
                                </div>
                            </div>
                            <!-- /.box-body -->

                            {{--  <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">News description <code>*</code>
                                        <small>put news description here</small>
                                    </h3>              
                                </div>
                                <!-- /.box-header -->
                                <div class="box-body pad">                                   
                                    <textarea class="textarea" id="editor1" name="description" placeholder="Place news contents here" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                </div>  --}}

                                <input type="hidden" name="admin_id" value="1">

                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('permission.index') }}" class="btn btn-warning">Back</a>
                                </div>
                            </div>             
                        </form>
                    </div>
                    <!-- /.box --> 
                </div><!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

app/resources/views/backend/permissions/edit.blade.php
@extends('backend/layouts/app')

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Permissions
                <small>add, edit, delete permissions section</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Permissions</a></li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Permission Section</h3>
                        </div>

                        @include('include/messages')
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('permission.update', $permission->id) }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                            <div class="box-body">
                                <!-- left column -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="news-head"> Permission Name<code>*</code></label>
                                        <input type="text" class="form-control" id="name" name="name" value="{{ $permission->name }}" placeholder="Enter Permission name ..">
                                    </div>

                                    <div class="form-group">
                                        <label for="for-permission"> Permission for <code>*</code></label>
                                        <select name="for_permission" id="for_permission" class="form-control" value="{{ $permission->for_permission }}">
                                            <option selected disable>Select Permission for </option>
                                            <option value="user">User</option>
                                            <option value="post">Post</option>
                                            <option value="other">Other</option>
                                        </select>
                                    </div>
                                </div>

                                

                                <!-- right column -->
                                <div class="col-md-6">

                                    
                                    
                                </div>
                            </div>
                            <!-- /.box-body -->

                            {{--  <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">News description <code>*</code>
                                        <small>put news description here</small>
                                    </h3>              
                                </div>
                                <!-- /.box-header -->
                                <div class="box-body pad">                                   
                                    <textarea class="textarea" id="editor1" name="description" placeholder="Place news contents here" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                </div>  --}}

                                <input type="hidden" name="admin_id" value="{{ $permission->admin_id }}">

                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('permission.index') }}" class="btn btn-warning">Back</a>
                                </div>
                            </div>             
                        </form>
                    </div>
                    <!-- /.box --> 
                </div><!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

app/resources/views/backend/permissions/index.blade.php
@extends('backend/layouts/app')

@section('headSection')
    <link rel="stylesheet" href="{{ asset('backend/plugins/datatables/dataTables.bootstrap.css') }}">
@endsection

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Permissions
                <small>add, edit, delete permissions section</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Permissions</a></li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box">
            <div class="box-header">
              <h3 class="box-title">Permission List</h3>

              @include('include.messages')

              @can('permission.create', Auth::user())
              <a href="{{ route('permission.create')}}" class="pull-right btn btn-primary">Add Permission</a>
              @endcan
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>ID</th>
                  <th>Permission Name</th>
                  <th>Permission For</th>
                  <th>Created at</th>
                  @can('permission.update', Auth::user())
                  <th>Edit</th>
                  @endcan

                  {{--  @can('permission.delete', Auth::user())
                  <th>Delete</th>
                  @endcan  --}}
                </tr>
                </thead>
                <tbody>
                @foreach($permissions as $permission)
                <tr>
                  <td>{{ $loop->index + 1 }}</td>
                  <td>{{ $permission->name}}</td>  
                  <td>{{ $permission->for_permission}}</td>  
                  
                  <td>{{ $permission->created_at}}</td>
                  <td><a href="{{ route('permission.edit', $permission->id)}}"><span class="glyphicon glyphicon-edit"></span></a></td>
                  {{--  <td>
                    <form id="delete-form-{{ $permission->id }}" method="post" action="{{ route('permission.destroy', $permission->id)}}" style="display:none;">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                    </form>
                    <a href="" onclick="
                        if(confirm('Are you sure, you want to delete this ?')) {
                            event.preventDefault();
                            document.getElementById('delete-form-{{ $permission->id}}').submit();
                        }
                        else
                        {
                            event.preventDefault();
                        }">
                        
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                  </td>  --}}
                </tr>      

                @endforeach
                </tbody>
                <tfoot>
                <tr>
                  <th>ID</th>
                  <th>Permission Name</th>
                  <th>Permission For</th>
                  <th>Created at</th>
                  @can('permission.update', Auth::user())
                  <th>Edit</th>
                  @endcan

                  {{--  @can('permission.delete', Auth::user())
                  <th>Delete</th>
                  @endcan  --}}
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
                </div><!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('footerSection')
    <script src="{{ asset('backend/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
    <!-- page script -->
    <script>
        $(function () {
            $("#example1").DataTable();
            $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false
            });
        });
    </script>
@endsection