app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Site Route
//Route::get('/', 'HomeController@index');
//Route::get('/open', 'HomeController@index');
Route::get('/', 'HomeController@index1');
Route::get('/home', 'HomeController@index1')->name('home');

// All Admin Route
Route::group(['namespace' => 'Admin'], function() {

    // Admin Auth Routes
    Route::get('admin-login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('admin-login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::get('register-schoolx', 'Auth\RegisterController@showRegistrationForm')->name('admin.register');
    Route::post('register-schoolx', 'Auth\RegisterController@register');
    
    // Dashboard Routes
    Route::get('admin-schoolx', 'AdminController@index')->name('admin-slf');

    // Users Route
    Route::resource('admin-schoolx/user', 'UserController');

    // Roles Route
    Route::resource('admin-schoolx/role', 'RoleController');

    // Permission Route
    Route::resource('admin-schoolx/permission', 'PermissionController');

    // News Routes
    Route::resource('admin-schoolx/news', 'NewsController');
    

});

Auth::routes();

app/app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;

use App\Model\admin\role;
use App\Model\admin\permission;

class RoleController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = role::all();
        return view ('backend.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->can('role.create')) {
            $permissions = permission::all();
            return view ('backend.roles.create', compact('permissions'));
         } 
        
        return redirect(route('admin-slf'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         //validation
        //return $request->all();
        $this->validate($request, [
            'name' => 'required|max:50|unique:roles',
        ]);

        $role = new role;

        $role->name = $request->name;
        $role->admin_id = $request->admin_id;

        $role->save();

        $role->permissions()->sync($request->permission);

        return redirect(route('role.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->can('role.update')) {
            $role = role::where('id', $id)->first();
            $permissions = permission::all();
            return view ('backend.roles.edit', compact('role', 'permissions'));
        } 

        return redirect(route('admin-slf'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validation
        $this->validate($request, [
            'name' => 'required|max:50',
        ]);

        $role = role::find($id);

        $role->name = $request->name;
        $role->admin_id = $request->admin_id;

        $role->save();

        $role->permissions()->sync($request->permission);

        return redirect(route('role.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        role::where('id', $id)->delete();
        return redirect()->back();
    }
}

app/resources/views/backend/roles/create.blade.php
@extends('backend/layouts/app')

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Roles
                <small>add, edit, delete roles section</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Roles</a></li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Roles Section</h3>
                        </div>

                        @include('include/messages')
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('role.store') }}" method="post">
                        {{ csrf_field() }}
                            <div class="box-body">
                                <!-- left column -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="news-head">Role Name <code>*</code></label>
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter Role name ..">
                                    </div>
                    
                                    
                                </div>

                                <!-- right column -->
                                 <div class="col-md-6">
                                    <br>
                                    <div class="checkbox" style="visibility: hidden">
                                        <label>
                                            <input type="checkbox" name="status"> Publish Role
                                        </label>
                                    </div>
                                    <br>
                                </div> 
                               
                                <div class="col-lg-4">
                                    <label for="news-head">Posts Permissions</label>
                                    @foreach ($permissions as $permission)
                                        @if ($permission->for_permission == 'post')
                                            <div class="checkbox">
                                                <label><input type="checkbox" name="permission[]" value="{{ $permission->id}}">{{ $permission->name }}</label>
                                            </div>
                                        @endif
                                    @endforeach
                                </div>

                                <div class="col-lg-4">
                                    <label for="news-head">Users Permissions</label>
                                    @foreach ($permissions as $permission)
                                        @if ($permission->for_permission == 'user')
                                            <div class="checkbox">
                                                <label><input type="checkbox" name="permission[]" value="{{ $permission->id}}">{{ $permission->name }}</label>
                                            </div>
                                        @endif
                                    @endforeach
                                </div>

                                <div class="col-lg-4">
                                    <label for="news-head">Other Permissions</label>
                                    @foreach ($permissions as $permission)
                                        @if ($permission->for_permission == 'other')
                                            <div class="checkbox">
                                                <label><input type="checkbox" name="permission[]" value="{{ $permission->id}}">{{ $permission->name }}</label>
                                            </div>
                                        @endif
                                    @endforeach
                                </div>




                            </div>

                            
                            <!-- /.box-body -->

                            <div class="box">

                                <input type="hidden" name="admin_id" value="1">

                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('role.index') }}" class="btn btn-warning">Back</a>
                                </div>
                            </div>             
                        </form>
                    </div>
                    <!-- /.box --> 
                </div><!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

app/resources/views/backend/roles/edit.blade.php
@extends('backend/layouts/app')

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Roles
                <small>add, edit, delete roles section</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Roles</a></li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Roles Section</h3>
                        </div>

                        @include('include/messages')
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('role.update', $role->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                            <div class="box-body">
                                <!-- left column -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="news-head">Role Name <code>*</code></label>
                                        <input type="text" class="form-control" id="name" name="name" value="{{ $role->name }}" placeholder="Enter Role name ..">
                                    </div>
                    
                                    
                                </div>

                                <!-- right column -->
                                 <div class="col-md-6">
                                    <br>
                                    <div class="checkbox" style="visibility: hidden">
                                        <label>
                                            <input type="checkbox" name="status"> Publish Role
                                        </label>
                                    </div>
                                    <br>
                                </div>

                                <div class="col-lg-4">
                                    <label for="news-head">Posts Permissions</label>
                                    @foreach ($permissions as $permission)
                                        @if ($permission->for_permission == 'post')
                                            <div class="checkbox">
                                                <label><input type="checkbox" name="permission[]" value="{{ $permission->id}}" 
                                                
                                                @foreach ($role->permissions as $role_permit)
                                                    @if ($role_permit->id == $permission->id)
                                                        checked
                                                    @endif
                                                @endforeach
                                                
                                                
                                                >{{ $permission->name }}
                                                </label>

                                                
                                            </div>
                                        @endif
                                    @endforeach
                                </div>

                                <div class="col-lg-4">
                                    <label for="news-head">Users Permissions</label>
                                    @foreach ($permissions as $permission)
                                        @if ($permission->for_permission == 'user')
                                            <div class="checkbox">
                                                <label><input type="checkbox" name="permission[]" value="{{ $permission->id}}"
                                                
                                                @foreach ($role->permissions as $role_permit)
                                                    @if ($role_permit->id == $permission->id)
                                                        checked
                                                    @endif
                                                @endforeach
                                                
                                                >{{ $permission->name }}</label>
                                            </div>
                                        @endif
                                    @endforeach
                                </div>

                                <div class="col-lg-4">
                                    <label for="news-head">Other Permissions</label>
                                    @foreach ($permissions as $permission)
                                        @if ($permission->for_permission == 'other')
                                            <div class="checkbox">
                                                <label><input type="checkbox" name="permission[]" value="{{ $permission->id}}"
                                                
                                                @foreach ($role->permissions as $role_permit)
                                                    @if ($role_permit->id == $permission->id)
                                                        checked
                                                    @endif
                                                @endforeach
                                                
                                                >{{ $permission->name }}</label>
                                            </div>
                                        @endif
                                    @endforeach
                                </div>



                            </div>
                            <!-- /.box-body -->

                            <div class="box">

                                <input type="hidden" name="admin_id" value="{{ $role->admin_id}}">

                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('role.index') }}" class="btn btn-warning">Back</a>
                                </div>
                            </div>             
                        </form>
                    </div>
                    <!-- /.box --> 
                </div><!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

app/resources/views/backend/roles/index.blade.php
@extends('backend/layouts/app')

@section('headSection')
    <link rel="stylesheet" href="{{ asset('backend/plugins/datatables/dataTables.bootstrap.css') }}">
@endsection

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Roles
                <small>add, edit, delete roles section</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Roles</a></li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box">
            <div class="box-header">
              <h3 class="box-title">Roles List</h3>
              @can('role.create', Auth::user())
              <a href="{{ route('role.create')}}" class="pull-right btn btn-primary">Add Role</a>
              @endcan
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>ID</th>
                  <th>Role Name</th>
                  {{--  <th>Publish</th>  --}}
                  <th>Created at</th>
                  @can('role.update', Auth::user())
                  <th>Edit</th>
                  @endcan

                  {{--  @can('role.delete', Auth::user())
                  <th>Delete</th>
                  @endcan  --}}
                </tr>
                </thead>
                <tbody>
                @foreach($roles as $role)
                <tr>
                  <td>{{ $loop->index + 1 }}</td>
                  <td>{{ $role->name}}</td>  
                  {{--  <td>
                    @if ($role->status == 1)
                        {{ "PUBLISH" }}
                    @else
                        {{ "NOT PUBLISH" }}
                    @endif
                </td>    --}}
                  <td>{{ $role->created_at}}</td>
                   @can('role.update', Auth::user())  
                  <td><a href="{{ route('role.edit', $role->id)}}"><span class="glyphicon glyphicon-edit"></span></a></td>
                  @endcan
                  {{--  @can('role.delete', Auth::user())
                  
                  <td>
                    <form id="delete-form-{{ $role->id }}" method="post" action="{{ route('role.destroy', $role->id)}}" style="display:none;">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                    </form>
                    <a href="" onclick="
                        if(confirm('Are you sure, you want to delete this ?')) {
                            event.preventDefault();
                            document.getElementById('delete-form-{{ $role->id}}').submit();
                        }
                        else
                        {
                            event.preventDefault();
                        }">
                        
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                  </td>  
                  @endcan
                  --}}
                </tr>      

                @endforeach
                </tbody>
                <tfoot>
               <tr>
                  <th>ID</th>
                  <th>Role Name</th>
                  {{--  <th>Publish</th>  --}}
                  <th>Created at</th>
                  @can('role.update', Auth::user())
                  <th>Edit</th>
                  @endcan

                  {{--  @can('role.delete', Auth::user())
                  <th>Delete</th>
                  @endcan  --}}
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
                </div><!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('footerSection')
    <script src="{{ asset('backend/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
    <!-- page script -->
    <script>
        $(function () {
            $("#example1").DataTable();
            $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false
            });
        });
    </script>
@endsection