app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Site Route
//Route::get('/', 'HomeController@index');
//Route::get('/open', 'HomeController@index');
Route::get('/', 'HomeController@index1');
Route::get('/home', 'HomeController@index1')->name('home');

// All Admin Route
Route::group(['namespace' => 'Admin'], function() {

    // Admin Auth Routes
    Route::get('admin-login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('admin-login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::get('register-schoolx', 'Auth\RegisterController@showRegistrationForm')->name('admin.register');
    Route::post('register-schoolx', 'Auth\RegisterController@register');
    
    // Dashboard Routes
    Route::get('admin-schoolx', 'AdminController@index')->name('admin-slf');

    // Users Route
    Route::resource('admin-schoolx/user', 'UserController');

    // Roles Route
    Route::resource('admin-schoolx/role', 'RoleController');

    // Permission Route
    Route::resource('admin-schoolx/permission', 'PermissionController');

    // News Routes
    Route::resource('admin-schoolx/news', 'NewsController');
    

});

Auth::routes();

app/app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;

use App\Model\admin\admin;
use App\Model\admin\role;


class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = admin::all();
        return view('backend/users/index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->can('user.create')) {
            $roles = role::all();
            return view('backend/users/create', compact('roles'));
        } 
        
        return redirect(route('admin-slf'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|unique:admins|email|max:255',
            'password' => 'required|confirmed',
        ]);

         $admin = new admin;

        if ($request->hasFile('image')) {
            $imageName = $request->image->store('public');
            $admin->image = $imageName;
        }

        $admin->name = $request->name;
        $admin->email = $request->email;
        $admin->password = bcrypt($request->password);
        $admin->status = $request->status? : $request->status=0;
        //$admin->password_confirmation = $request->password_confirmation;
        $admin->phone = $request->phone;
        $admin->address = $request->address; 
        $admin->admin_id = $request->admin_id; 

        $admin->save();

        $admin->roles()->sync($request->role_id);

        return redirect(route('user.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->can('user.update')) {
            $user = admin::where('id', $id)->first();
            $roles = role::all();
            return view('backend.users.edit', compact('user', 'roles'));
        } 

        return redirect(route('admin-schoolx'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validation
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|max:255',
            //'password' => 'required|confirmed',
            //'role_id' => 'required',
        ]);

        if ($request->hasFile('image')) {
            $imageName = $request->image->store('public');
        } else {
            $result = admin::where('id', $id)->first();
            $imageName = $result->image;
        }

        $admin = admin::find($id);

        //return $admin;

        $admin->name = $request->name;
        $admin->email = $request->email;
        $admin->image = $imageName;
        //$admin->password = $request->password;
        $admin->status = $request->status? : $request->status=0;
        //$admin->password_confirmation = $request->password_confirmation;
        $admin->phone = $request->phone;
        $admin->address = $request->address;
        $admin->admin_id = $request->admin_id;
        //$admin->role_id = $request->role_id;

        $admin->save();

        $admin->roles()->sync($request->role_id);

        return redirect(route('user.index'));
    } 

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        admin::where('id', $id)->delete();
        return redirect()->back();
    }
}

app/resources/views/backend/users/create.blade.php
@extends('backend/layouts/app')

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Users
                <small>add, edit, delete users section</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Users</a></li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Users Section</h3>
                        </div>

                        @include('include/messages')
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('user.store') }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                            <div class="box-body">
                                <!-- left column -->
                                <div class="col-md-6"> 
                                    <div class="form-group">
                                        <label for="news-head">Name <code>*</code></label>
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter user name ..">
                                    </div>

                                    <div class="form-group">
                                        <label for="news-head">Email <code>*</code></label>
                                        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email address ..">
                                    </div>

                                    <div class="form-group">
                                        <label for="news-head">Password <code>*</code></label>
                                        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password ..">
                                    </div>

                                    <div class="form-group">
                                        <label for="news-head">Confirm Password <code>*</code></label>
                                        <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Enter password again ..">
                                    </div>  

                                    @can('user.delete', Auth::user())
                                    <div class="form-group">
                                        <label>Assign Role</label>   
                                        <div class="row"> 
                                            @foreach ($roles as $role) 
                                            <div class="col-lg-3">                                
                                                <div class="checkbox">
                                                    <label>
                                                        <input type="checkbox" name="role_id[]" value="{{ $role->id }}"> {{ $role->name }}
                                                    </label>
                                                </div>
                                            </div>
                                            @endforeach
                                        </div>
                                        
                                    </div>
                                    @endcan

                                    

                                </div>

                                <!-- right column -->
                                <div class="col-md-6">

                                    <div class="form-group">
                                        <label for="image">User Image</label>
                                        <input type="file" id="image" name="image">
                                        <p class="help-block">put user image here</p>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label for="news-head">Telephone </label>
                                        <input type="text" class="form-control" id="phone" name="phone" placeholder="Enter phone number ..">
                                    </div>

                                    <div class="form-group">
                                        <label for="news-head">Address </label>
                                        <textarea class="form-control" name="address" placeholder="Enter address..." rows="3"></textarea>
                                    </div>

                                    @can('user.delete', Auth::user())
                                    <br>
                                    <div class="form-group">
                                        <label for="news-head">Active User </label>
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="status" value="1"> Active User
                                            </label>
                                        </div>
                                    </div>
                                    @endcan



                                    

                                </div>
                            </div>
                            <!-- /.box-body -->

                            {{--  <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">News description <code>*</code>
                                        <small>put news description here</small>
                                    </h3>              
                                </div>
                                <!-- /.box-header -->
                                <div class="box-body pad">                                   
                                    <textarea class="textarea" id="editor1" name="description" placeholder="Place news contents here" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                </div>  --}}

                                <input type="hidden" name="admin_id" value="1">

                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('user.index') }}" class="btn btn-warning">Back</a>
                                </div>
                            </div>             
                        </form>
                    </div>
                    <!-- /.box --> 
                </div><!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

app/resources/views/backend/users/edit.blade.php
@extends('backend/layouts/app')

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Users
                <small>add, edit, delete users section</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Users</a></li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Users Section</h3>
                        </div>

                        @include('include/messages')
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('user.update', $user->id) }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{ method_field('PATCH')}}
                            <div class="box-body">
                                <!-- left column -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="news-head">Name <code>*</code></label>
                                        <input type="text" class="form-control" id="name" name="name" value="{{ $user->name}}" placeholder="Enter user name ..">
                                    </div>

                                    <div class="form-group">
                                        <label for="news-head">Email <code>*</code></label>
                                        <input type="email" class="form-control" id="email" name="email" value="{{ $user->email }}" placeholder="Enter email address ..">
                                    </div>
                                    @can('user.delete', Auth::user())
                                    <div class="form-group">
                                        <label>Assign Role</label>
                                        <div class="row">
                                            @foreach ($roles as $role)
                                            <div class="col-lg-3">                                
                                                <div class="checkbox">
                                                    <label>
                                                        <input type="checkbox" name="role_id[]" value="{{ $role->id }}" 
                                                        
                                                        @foreach ($user->roles as $user_role)
                                                            @if ($user_role->id == $role->id)
                                                                checked
                                                            @endif
                                                        @endforeach
                                                        
                                                        > {{ $role->name }}
                                                    </label>
                                                </div>
                                            </div>
                                            @endforeach
                                        </div>
                                        
                                    </div>
                                    @endcan

                                    

                                </div>

                                <!-- right column -->
                                <div class="col-md-6">

                                    <div class="form-group">
                                        <label for="image">User Image</label>
                                            <br>
                                            <img src="{{ Storage::disk('local')->url($user->image) }}" style="width: 50px; height:20px">
                                            <br>
                                            <br>
                                        <input type="file" id="image" name="image">
                                        <p class="help-block">put user image here</p>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label for="news-head">Telephone </label>
                                        <input type="text" class="form-control" id="phone" name="phone" value="{{ $user->phone }}" placeholder="Enter phone number ..">
                                    </div>

                                    <div class="form-group">
                                        <label for="news-head">Address </label>
                                        <textarea class="form-control" name="address" placeholder="Enter address..." rows="3">{{ $user->address }}</textarea>
                                    </div>

                                    @can('user.delete', Auth::user())
                                    <br>
                                    <div class="form-group">
                                        <label for="news-head">Active User </label>
                                        <div class="checkbox" >
                                            <label>
                                                <input type="checkbox" name="status" value="1" @if ($user->status == 1) checked @endif> Active User
                                            </label>
                                        </div>
                                    </div>
                                    @endcan

                                    
                                    


                                    

                                </div>
                            </div>
                            <!-- /.box-body -->

                            {{--  <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">News description <code>*</code>
                                        <small>put news description here</small>
                                    </h3>              
                                </div>
                                <!-- /.box-header -->
                                <div class="box-body pad">                                   
                                    <textarea class="textarea" id="editor1" name="description" placeholder="Place news contents here" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                </div>  --}}

                                <input type="hidden" name="admin_id" value="{{ $user->admin_id }}">

                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('user.index') }}" class="btn btn-warning">Back</a>
                                </div>
                            </div>             
                        </form>
                    </div>
                    <!-- /.box --> 
                </div><!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

app/resources/views/backend/users/index.blade.php
@extends('backend/layouts/app')

@section('headSection')
    <link rel="stylesheet" href="{{ asset('backend/plugins/datatables/dataTables.bootstrap.css') }}">
@endsection

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Users
                <small>add, edit, delete users section</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Users</a></li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box">
            <div class="box-header">
              <h3 class="box-title">User List</h3>
              @can('user.create', Auth::user())
              <a href="{{ route('user.create')}}" class="pull-right btn btn-primary">Add User</a>
              @endcan
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>User ID</th>
                  <th>User Name</th>
                  <th>Assigned Role</th>
                  <th>Status</th>
                  <th>Email</th>
                  <th>Created at</th>
                  @can('user.update', Auth::user())
                    <th>Edit</th>
                  @endcan

                  @can('user.delete', Auth::user())
                    <th>Delete</th>
                  @endcan
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                <tr>
                  <td>{{ $loop->index + 1 }}</td>
                  <td>{{ $user->name}}</td>  
                  <td>
                    @foreach ($user->roles as $role)
                        {{ $role->name}},
                    @endforeach
                  </td>
                  <td>{{ $user->status? 'Active' : 'Not Active'}}</td>  
                  <td>{{ $user->email}}</td>  
                  {{--  <td><img src="{{ Storage::disk('local')->url($user->image) }}" style="width: 50px; height:20px"></td>    --}}
                  {{--  <td>
                    @if ($user->status == 1)
                        {{ "PUBLISH" }}
                    @else
                        {{ "NOT PUBLISH" }}
                    @endif
                </td>      --}}
                  <td>{{ $user->created_at}}</td> 
                  @can('user.update', Auth::user()) 
                  <td><a href="{{ route('user.edit', $user->id)}}"><span class="glyphicon glyphicon-edit"></span></a></td>
                  @endcan

                  @can('user.delete', Auth::user())
                  <td>
                    <form id="delete-form-{{ $user->id }}" method="post" action="{{ route('user.destroy', $user->id)}}" style="display:none;">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                    </form>
                    <a href="" onclick="
                        if(confirm('Are you sure, you want to delete this ?')) {
                            event.preventDefault();
                            document.getElementById('delete-form-{{ $user->id}}').submit();
                        }
                        else
                        {
                            event.preventDefault();
                        }">
                        
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                  </td>
                  @endcan
                </tr>      

                @endforeach
                </tbody>
                <tfoot>
                <tr>
                  <th>User ID</th>
                  <th>User Name</th>
                  <th>Assigned Role</th>
                  <th>Status</th>
                  <th>Email</th>
                  <th>Created at</th>
                  @can('user.update', Auth::user())
                    <th>Edit</th>
                  @endcan
                  
                  @can('user.delete', Auth::user())
                    <th>Delete</th>
                  @endcan
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
                </div><!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('footerSection')
    <script src="{{ asset('backend/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
    <!-- page script -->
    <script>
        $(function () {
            $("#example1").DataTable();
            $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false
            });
        });
    </script>
@endsection