app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Site Route
//Route::get('/', 'HomeController@index');
//Route::get('/open', 'HomeController@index');
Route::get('/', 'HomeController@index1');
Route::get('/home', 'HomeController@index1')->name('home');

// All Admin Route
Route::group(['namespace' => 'Admin'], function() {

    // Admin Auth Routes
    Route::get('admin-login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('admin-login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::get('register-schoolx', 'Auth\RegisterController@showRegistrationForm')->name('admin.register');
    Route::post('register-schoolx', 'Auth\RegisterController@register');
    
    // Dashboard Routes
    Route::get('admin-schoolx', 'AdminController@index')->name('admin-slf');

    // Users Route
    Route::resource('admin-schoolx/user', 'UserController');

    // Roles Route
    Route::resource('admin-schoolx/role', 'RoleController');

    // Permission Route
    Route::resource('admin-schoolx/permission', 'PermissionController');

    // News Routes
    Route::resource('admin-schoolx/news', 'NewsController');
    

});

Auth::routes();

app/resources/views/backend/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    @include('backend/layouts/head')
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        @include('backend/layouts/header')
    </header>

  
  <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
            @include('backend/layouts/left-nav')
    </aside>

  <!-- Content Wrapper. Contains page content -->

    @section('main-content')
        @show

  <!-- /.content-wrapper -->

  <footer class="main-footer">

    @include('backend/layouts/footer')
  
</body>
</html>

app/resources/views/backend/layouts/footer.blade.php
<div class="pull-right hidden-xs">
      <b>Version</b> 1
    </div>
    <strong>Copyright &copy; {{ Carbon\carbon::now()->year }} <a href="#" target="_blank">schoolx</a>.</strong> All rights
    reserved.

    </footer>

  
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="{{ asset('backend/plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="{{ asset('backend/bootstrap/js/bootstrap.min.js') }}"></script>
<!-- Morris.js charts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="{{ asset('backend/plugins/morris/morris.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('backend/plugins/sparkline/jquery.sparkline.min.js') }}"></script>
<!-- jvectormap -->
<script src="{{ asset('backend/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
<script src="{{ asset('backend/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('backend/plugins/knob/jquery.knob.js') }}"></script>
<!-- daterangepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="{{ asset('backend/plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- datepicker -->
<script src="{{ asset('backend/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ asset('backend/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
<!-- Slimscroll -->
<script src="{{ asset('backend/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('backend/plugins/fastclick/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('backend/dist/js/app.min.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<!-- <script src="{{ asset('backend/dist/js/pages/dashboard.js') }}"></script> -->
<!-- AdminLTE for demo purposes -->
 <script src="{{ asset('backend/dist/js/demo.js') }}"></script>
<!-- CK Editor -->
{{--  <script src="https://cdn.ckeditor.com/4.5.7/standard/ckeditor.js"></script>  --}}


@section('footerSection')
  @show

app/resources/views/backend/layouts/head.blade.php
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>SchoolX | Dashboard</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{{ asset('backend/bootstrap/css/bootstrap.min.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('backend/dist/css/AdminLTE.min.css') }}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{ asset('backend/dist/css/skins/_all-skins.min.css') }}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{ asset('backend/plugins/iCheck/flat/blue.css') }}">
  <!-- Morris chart -->
  <link rel="stylesheet" href="{{ asset('backend/plugins/morris/morris.css') }}">
  <!-- jvectormap -->
  <link rel="stylesheet" href="{{ asset('backend/plugins/jvectormap/jquery-jvectormap-1.2.2.css') }}">
  <!-- Date Picker -->
  <link rel="stylesheet" href="{{ asset('backend/plugins/datepicker/datepicker3.css') }}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{ asset('backend/plugins/daterangepicker/daterangepicker.css') }}">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="{{ asset('backend/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">

  @section('headSection')
    @show

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

app/resources/views/backend/layouts/header.blade.php
    <!-- Logo -->
    <a href="/admin-schoolx" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>ABC</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Web</b>ABC</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          
          <!-- Notifications: style can be found in dropdown.less -->
          
          <!-- Tasks: style can be found in dropdown.less -->
         
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            @if (Auth::user()->image !== NULL)
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{ Storage::disk('local')->url(Auth::user()->image) }}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ Auth::user()->name }}</span>
            </a>
            @else
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{ asset('backend/dist/img/user2-160x160.jpg')}}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ Auth::user()->name }}</span>
            </a>
            @endif
            <ul class="dropdown-menu">
              <!-- User image -->
              @if (Auth::user()->image !== NULL)
              <li class="user-header">
                <img src="{{ Storage::disk('local')->url(Auth::user()->image) }}"  alt="user image" class="img-circle">
                
                <p>
                  {{ Auth::user()->name }} - SchoolX User
                  <small>Member since {{ Auth::user()->created_at->toFormattedDateString() }}</small> 
                </p>
              </li>
              @else 
              <li class="user-header">
                <img src="{{ asset('backend/dist/img/user2-160x160.jpg')}}"  alt="user image" class="img-circle">
                
                <p>
                  {{ Auth::user()->name }} - SchoolX User
                  <small>Member since {{ Auth::user()->created_at->toFormattedDateString() }}</small> 
                </p>
              </li>
              @endif           
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-warning btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  
                        <a href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                                      document.getElementById('logout-form').submit();" class="btn btn-primary btn-flat">
                            Logout
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <!-- <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li> -->
        </ul>
      </div>
    </nav>

app/resources/views/backend/layouts/home.blade.php
@extends('backend/layouts/app')

@section('main-content')

    <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Admin Panel
        <small>it all starts here</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Admin panel</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Dashboard</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            
          </div>
        </div>
        <div class="box-body" style="height:400px;text-align:center;">

        </div>
        <!-- /.box-body -->
        
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
  </div>
@endsection
  

app/resources/views/backend/layouts/left-nav.blade.php
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        @if (Auth::user()->image !== NULL)
        <div class="pull-left image">
          <img src="{{ Storage::disk('local')->url(Auth::user()->image) }}" class="img-circle" alt="User Image">
        </div>
        @else
        <div class="pull-left image">
          <img src="{{ asset('backend/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
        </div>
        @endif
        <div class="pull-left info">
          <p>{{ Auth::user()->name }}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>


        @if (Gate::check('news.update') || Gate::check('news.delete'))
          <li class="treeview">
          <a href="{{ route('news.index')}}">
            <i class="fa fa-newspaper-o" aria-hidden="true"></i> <span>News</span>          
          </a>
        </li>
        @endif

        <li class="header">ADMIN AREA</li>

        <li class="treeview active">
          <a href="#">
            <i class="fa fa-folder"></i> <span>Admin</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            @if (Gate::check('user.create') || Gate::check('user.update') || Gate::check('user.delete'))
              <li><a href="{{ route('user.index') }}"><i class="fa fa-circle-o"></i> Users</a></li>
            @endif

             @if (Gate::check('role.create') || Gate::check('role.update') || Gate::check('role.delete'))
            <li><a href="{{ route('role.index') }}"><i class="fa fa-circle-o"></i> Roles</a></li>
            @endif

            @if (Gate::check('permission.create') || Gate::check('permission.update') || Gate::check('permission.delete'))
            <li><a href="{{ route('permission.index') }}"><i class="fa fa-circle-o"></i> Permissions</a></li>
            @endif

          </ul>
        </li>

      </ul>
    </section>
    <!-- /.sidebar -->

app/resources/views/backend/layouts/temp_app.blade.php
<!DOCTYPE html>
<html>
<head>
    @include('backend/layouts/head')
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        {{--  @include('backend/layouts/header')  --}}
    </header>

  
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
        {{--  @include('backend/layouts/left-nav')  --}}
  </aside>

  <!-- Content Wrapper. Contains page content -->

     @section('main-content')
        @show

  <!-- /.content-wrapper -->

  <footer class="main-footer">

    @include('backend/layouts/footer')
  
</body>
</html>